version: 2.1

orbs:
  saucelabs: saucelabs/sauce-connect@1.0.1

partials:
    node-image: &node-image circleci/node:12.14.1

jobs:
  yarn-install:
    docker:
      - image: *node-image
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-install-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - yarn-install-{{ checksum "package.json" }}
            - yarn-install
          paths:
            - node_modules
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-install-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  lint:
    docker:
      - image: *node-image
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint:js
      - run: yarn lint:css

  lint-docker:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run:
          name: Lint .production/Dockerfile
          command: hadolint .production/Dockerfile
      - run:
          name: Lint docker/selenium/Dockerfile
          command: hadolint docker/selenium/Dockerfile
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  build:
    docker:
      - image: *node-image
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  unit-tests:
    docker:
      - image: *node-image
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: yarn test

  functional-tests:
    docker:
      - image: *node-image
        environment:
          DATABASE_HOST: localhost
          DATABASE_USER: thetribe
          DATABASE_NAME: thetribe
          DATABASE_PASSWORD: 424242
          SAUCELABS_HOST: localhost
      - image: circleci/postgres:10.7
        environment:
          POSTGRES_USER: thetribe
          POSTGRES_PASSWORD: 424242
          POSTGRES_DB: thetribe
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run migrations
          command: yarn sequelize db:migrate
      - run:
          name: Start application
          command: yarn start
          background: true
      - run:
          name: Setup host
          command: echo '127.0.0.1 app.local' | sudo tee -a /etc/hosts
      - run:
          name: Wait for app
          command: 'dockerize -wait http://app.local:3000 -wait-http-header "Accept: */*" -timeout 1m'
      - saucelabs/install
      - saucelabs/open_tunnel:
          tunnel_identifier: $CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM
      - run:
          name: Run tests
          command: |
            export SAUCELABS_TUNNEL_IDENTIFIER=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM

            yarn test:func:sauce:chrome
            yarn test:func:sauce:firefox
            #yarn test:func:sauce:ie
            #yarn test:func:sauce:safari
      - saucelabs/close_tunnel

# Example of Sentry release & sourcemap upload job
# TODO while bootstrapping, setup your projet name, uncomment the job and uncomment
# it's call in workflows
# Note: You may need multiple sentry jobs if you have an app and an api for example
#
#  sentry-release:
#    docker:
#      - image: getsentry/sentry-cli:1.40.0
#        entrypoint: ''
#        environment:
#          SENTRY_PROJECT: DEFINE-YOUR-PROJECT-NAME-HERE
#    steps:
#      - attach_workspace:
#          at: ~/project
#      - run: sentry-cli releases new --project ${SENTRY_PROJECT} ${SENTRY_PROJECT}@${CIRCLE_SHA1}
#      - run: sentry-cli releases files ${SENTRY_PROJECT}@${CIRCLE_SHA1} upload-sourcemaps build --ignore '*.css.map'
#      - run: sentry-cli releases finalize ${SENTRY_PROJECT}@${CIRCLE_SHA1}

workflows:
  version: 2

  build:
    jobs:
      - yarn-install
      - lint:
          requires:
            - yarn-install
      - lint-docker
      - build:
          requires:
            - yarn-install
      - unit-tests:
          requires:
            - yarn-install
      - functional-tests:
          context: saucelabs
          requires:
            - yarn-install
# TODO while bootstrapping, uncomment this block to activate workflow
#      - sentry-release:
#          context: sentry
#          requires:
#            - build
#          filters:
#            branches:
#              only:
#                - develop
#                - master
